version: '3.8'
name: project-mart
services:
  product-service:
    build:
      context: ./product_service
      dockerfile: Dockerfile.dev
    container_name: product-service
    volumes:
      - ./product_service:/code  # Sync local development directory with the container
    depends_on:
        - postgres_db
        - broker
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
  inventory-service:
    build:
      context: ./inventory_service
      dockerfile: Dockerfile.dev
    container_name: inventory-service
    volumes:
      - ./inventory_service:/code  # Sync local development directory with the container
    depends_on:
        - postgres_db
        - broker
    ports:
      - "8002:8000"  # Expose container port 8000 to host port 8000
  notification-service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile.dev
    container_name: notification-service
    volumes:
      - ./notification_service:/code  # Sync local development directory with the container
    depends_on:
        - postgres_db
        - broker
    ports:
      - "8007:8000"  # Expose container port 8000 to host port 8000
  payment-service:
    build:
      context: ./payment_service
      dockerfile: Dockerfile.dev
    container_name: payment-service
    volumes:
      - ./payment_service:/code  # Sync local development directory with the container
    depends_on:
        - postgres_db
        - broker
    ports:
      - "8008:8000"  # Expose container port 8000 to host port 8000 
  order-service:

    build:
      context: ./order_service
      dockerfile: Dockerfile.dev
    container_name: order-service
    volumes:
      - ./order_service:/code  # Sync local development directory with the container
    depends_on:
        - postgres_db
        - broker
    ports:
      - "8004:8000"  # Expose container port 8000 to host port 8000
  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile.dev
    container_name: user-service
    volumes:
      - ./user_service:/code  # Sync local development directory with the container
    depends_on:
        - postgres_db
        - broker
    ports:
      - "8011:8000"  # Expose container port 8000 to host port 8000
  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: postgres-container
    environment:
        - POSTGRES_USER=ziakhan
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=mydatabase
    ports:
        - '5434:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: 'Local Kafka Cluster'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:19092'
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - broker
volumes:
  postgres_db:
    driver: local
networks:
  default:
    driver: bridge

