# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"Y\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"3\n\x0eProductRequest\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"\"\n\x0fProductResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9d\x02\n\x0eProductService\x12\x42\n\rCreateProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12?\n\nGetProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12\x42\n\rUpdateProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponse\x12\x42\n\rDeleteProduct\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=26
  _PRODUCT._serialized_end=115
  _PRODUCTREQUEST._serialized_start=117
  _PRODUCTREQUEST._serialized_end=168
  _PRODUCTRESPONSE._serialized_start=170
  _PRODUCTRESPONSE._serialized_end=204
  _PRODUCTSERVICE._serialized_start=207
  _PRODUCTSERVICE._serialized_end=492
# @@protoc_insertion_point(module_scope)
